name: Martyn Payne Photography
favicon: null
layout_spectrum: 0.76037
typography_spectrum: 0.15608527325093746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6875
  lightness: 0.7964231104124337
  saturation: 0.47166453767567873
  rhythmicContrast: 1
purpose: []
